const PRODUCTS = [
  /* ── VINOS ── */
  { id: 1,  nombre: "Vino Albariño Mar de Frades",         precio: 17.66, categoria: "vinos", subcategoria: "albarino",  imagen: "https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=400&q=80", badge: "Destacado", descripcion: "Vino blanco gallego de la D.O. Rías Baixas.", graduacion: "12,5%", volumen: "750 ml", bodega: "Mar de Frades" },
  { id: 2,  nombre: "Vino Ramón Bilbao Crianza",           precio: 8.80,  categoria: "vinos", subcategoria: "rioja",     imagen: "https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&q=80", badge: "Más Vendido", descripcion: "Tinto crianza de Rioja con 12 meses en barrica.", graduacion: "13,5%", volumen: "750 ml", bodega: "Ramón Bilbao" },
  { id: 3,  nombre: "Vino Monte Real Gran Reserva",        precio: 23.99, categoria: "vinos", subcategoria: "rioja",     imagen: "https://images.unsplash.com/photo-1547595628-b0c42b4ea0b0?w=400&q=80", badge: "Premium", descripcion: "Gran Reserva excepcional de Rioja.", graduacion: "13,5%", volumen: "750 ml", bodega: "Monte Real" },
  { id: 4,  nombre: "Vino Albariño Paco & Lola",           precio: 13.95, categoria: "vinos", subcategoria: "albarino",  imagen: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=400&q=80", badge: null, descripcion: "Albariño fresco y aromático de Rías Baixas.", graduacion: "12,5%", volumen: "750 ml", bodega: "Paco & Lola" },
  { id: 5,  nombre: "Vino Albariño Fillaboa",              precio: 14.54, categoria: "vinos", subcategoria: "albarino",  imagen: "https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=400&q=80", badge: null, descripcion: "Albariño elegante con notas minerales.", graduacion: "13%", volumen: "750 ml", bodega: "Fillaboa" },
  { id: 6,  nombre: "Vino Ribera del Duero Proventus",     precio: 20.09, categoria: "vinos", subcategoria: "ribera",    imagen: "https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&q=80", badge: null, descripcion: "Tinto de Ribera del Duero con 18 meses en barrica.", graduacion: "14%", volumen: "750 ml", bodega: "Proventus" },
  { id: 7,  nombre: "Vino Rioja Ondipuerko Rosado",        precio: 15.16, categoria: "vinos", subcategoria: "rosado",    imagen: "https://images.unsplash.com/photo-1560148218-1a83060f7b32?w=400&q=80", badge: "Destacado", descripcion: "Rosado moderno de Rioja con aromas a fresa.", graduacion: "12,5%", volumen: "750 ml", bodega: "Ondipuerko" },
  { id: 8,  nombre: "Vino Rioja Centvm Vitis",             precio: 123.25,categoria: "vinos", subcategoria: "rioja",     imagen: "https://images.unsplash.com/photo-1547595628-b0c42b4ea0b0?w=400&q=80", badge: "Premium", descripcion: "Vino de culto de Rioja, expresión máxima del Tempranillo.", graduacion: "14,5%", volumen: "750 ml", bodega: "Centvm Vitis" },
  { id: 9,  nombre: "Vino Lágrimas de María Crianza",      precio: 6.16,  categoria: "vinos", subcategoria: "rioja",     imagen: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&q=80", badge: null, descripcion: "Crianza accesible y afrutado de Rioja.", graduacion: "13%", volumen: "750 ml", bodega: "Lágrimas de María" },
  { id: 10, nombre: "PEREGRINO ROSADO",                    precio: 4.99,  categoria: "vinos", subcategoria: "rosado",    imagen: "https://images.unsplash.com/photo-1560148218-1a83060f7b32?w=400&q=80", badge: null, descripcion: "Rosado fresco y frutal, perfecto para el verano.", graduacion: "12%", volumen: "750 ml", bodega: "Peregrino" },
  { id: 11, nombre: "Vino Espumoso Brut Nature Mar de Frades", precio: 21.39, categoria: "vinos", subcategoria: "espumoso", imagen: "https://images.unsplash.com/photo-1585553616435-2dc0a54e1c8f?w=400&q=80", badge: null, descripcion: "Espumoso gallego elaborado con Albariño.", graduacion: "11,5%", volumen: "750 ml", bodega: "Mar de Frades" },
  { id: 12, nombre: "Vino Dulce Sanson Original",          precio: 5.75,  categoria: "vinos", subcategoria: "dulces",    imagen: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&q=80", badge: null, descripcion: "Vino dulce de intenso aroma, ideal para postres.", graduacion: "15%", volumen: "750 ml", bodega: "Sanson" },
  { id: 13, nombre: "Vino Matarromera Reserva",            precio: 42.24, categoria: "vinos", subcategoria: "ribera",    imagen: "https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&q=80", badge: "Premium", descripcion: "Reserva de Ribera del Duero con crianza en barrica francesa.", graduacion: "14%", volumen: "750 ml", bodega: "Matarromera" },
  { id: 14, nombre: "Vino Godello Luar Do Sil",            precio: 11.20, categoria: "vinos", subcategoria: "godello",   imagen: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=400&q=80", badge: null, descripcion: "Godello fresco y mineral de Valdeorras.", graduacion: "13%", volumen: "750 ml", bodega: "Luar Do Sil" },
  /* ── DESTILADOS ── */
  { id: 15, nombre: "Ginebra Cubical Premium",             precio: 22.51, categoria: "destilados", subcategoria: "ginebra", imagen: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=400&q=80", badge: "Destacado", descripcion: "Ginebra premium con aromas cítricos y botánicos.", graduacion: "40%", volumen: "700 ml", bodega: "William & Humbert" },
  { id: 16, nombre: "Whisky Old Parr 1L",                  precio: 42.93, categoria: "destilados", subcategoria: "whisky",  imagen: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&q=80", badge: null, descripcion: "Blend escocés con notas de miel y turba.", graduacion: "40%", volumen: "1000 ml", bodega: "Old Parr" },
  { id: 17, nombre: "Orujo Fillaboa Reserva Especial",     precio: 42.93, categoria: "destilados", subcategoria: "orujo",   imagen: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&q=80", badge: "Más Vendido", descripcion: "Orujo gallego de alta calidad, suave y aromático.", graduacion: "40%", volumen: "700 ml", bodega: "Fillaboa" },
  { id: 18, nombre: "Ginebra Hendrick's",                  precio: 33.14, categoria: "destilados", subcategoria: "ginebra", imagen: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=400&q=80", badge: null, descripcion: "Ginebra escocesa con pepino y pétalos de rosa.", graduacion: "41,4%", volumen: "700 ml", bodega: "Hendrick's" },
  { id: 19, nombre: "Ginebra Nordés",                      precio: 24.41, categoria: "destilados", subcategoria: "ginebra", imagen: "https://images.unsplash.com/photo-1608885898957-0d838992e515?w=400&q=80", badge: null, descripcion: "Ginebra gallega con 11 botánicos autóctonos.", graduacion: "40%", volumen: "700 ml", bodega: "Nordés" },
  { id: 20, nombre: "Ron Zacapa Centenario",               precio: 54.13, categoria: "destilados", subcategoria: "ron",     imagen: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&q=80", badge: "Premium", descripcion: "Ron guatemalteco añejo con notas de caramelo y vainilla.", graduacion: "40%", volumen: "700 ml", bodega: "Zacapa" },
  { id: 21, nombre: "El Afilador Crema de Orujo",          precio: 11.30, categoria: "destilados", subcategoria: "orujo",   imagen: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&q=80", badge: null, descripcion: "Crema de orujo gallega suave y cremosa.", graduacion: "17%", volumen: "700 ml", bodega: "El Afilador" },
  { id: 22, nombre: "Vermouth Martini Rosso",              precio: 10.04, categoria: "destilados", subcategoria: "vermouth", imagen: "https://images.unsplash.com/photo-1560148218-1a83060f7b32?w=400&q=80", badge: null, descripcion: "Vermouth clásico italiano, dulce y aromático.", graduacion: "15%", volumen: "750 ml", bodega: "Martini" },
  { id: 23, nombre: "Brandy Gran Duque de Alba",           precio: 24.85, categoria: "destilados", subcategoria: "brandy",  imagen: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&q=80", badge: null, descripcion: "Brandy de Jerez con crianza en botas de Pedro Ximénez.", graduacion: "36%", volumen: "700 ml", bodega: "González Byass" },
  /* ── GOURMET ── */
  { id: 24, nombre: "Bonito del Norte Ortiz 260g",         precio: 6.90,  categoria: "gourmet", subcategoria: "conservas", imagen: "https://images.unsplash.com/photo-1603073163308-9654c3fb70b5?w=400&q=80", badge: "Más Vendido", descripcion: "Bonito del norte en aceite de oliva virgen extra.", graduacion: null, volumen: "260 g", bodega: "Ortiz" },
  { id: 25, nombre: "Queso Curado de Oveja 3 KG",         precio: 70.46, categoria: "gourmet", subcategoria: "quesos",    imagen: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80", badge: null, descripcion: "Queso curado de oveja de Zamora, sabor intenso.", graduacion: null, volumen: "±3 Kg", bodega: "Sansueña" },
  { id: 26, nombre: "Jamón Ibérico 100% Bellota",         precio: 565.00,categoria: "gourmet", subcategoria: "jamon",     imagen: "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?w=400&q=80", badge: "Exclusivo", descripcion: "Jamón 100% ibérico de bellota, curación mínima 36 meses.", graduacion: null, volumen: "±7 Kg", bodega: "A. Sánchez" },
  { id: 27, nombre: "Aceite de Oliva Virgen Extra Iznaoliva", precio: 26.00, categoria: "gourmet", subcategoria: "aceite", imagen: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&q=80", badge: null, descripcion: "AOVE de primera extracción en frío, sabor afrutado.", graduacion: null, volumen: "500 ml", bodega: "Iznaoliva" },
  { id: 28, nombre: "Mejillón Ría de Arosa Ortiz 4/6",    precio: 8.75,  categoria: "gourmet", subcategoria: "conservas", imagen: "https://images.unsplash.com/photo-1603073163308-9654c3fb70b5?w=400&q=80", badge: null, descripcion: "Mejillones en escabeche de las Rías Gallegas.", graduacion: null, volumen: "115 g", bodega: "Ortiz" },
  { id: 29, nombre: "Pulpo a la Gallega",                  precio: 13.66, categoria: "gourmet", subcategoria: "conservas", imagen: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80", badge: "Local", descripcion: "Pulpo cocido a la gallega con pimentón de la Vera.", graduacion: null, volumen: "280 g", bodega: "Galicia" },
  { id: 30, nombre: "Paleta de Bellota 100% Ibérica",     precio: 139.00,categoria: "gourmet", subcategoria: "jamon",     imagen: "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?w=400&q=80", badge: null, descripcion: "Paleta ibérica 100% bellota, sabor intenso y textura suave.", graduacion: null, volumen: "±4 Kg", bodega: "A. Sánchez" },
  /* ── DULCE ── */
  { id: 31, nombre: "Chocolate Negro 95% Cacao",           precio: 3.39,  categoria: "dulce", subcategoria: "chocolates", imagen: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&q=80", badge: null, descripcion: "Chocolate negro intenso, amargo y rico en polifenoles.", graduacion: null, volumen: "100 g", bodega: "Lindt" },
  { id: 32, nombre: "Bombones Piedras de Portomarín",      precio: 8.00,  categoria: "dulce", subcategoria: "bombones",   imagen: "https://images.unsplash.com/photo-1575377427642-087cf684f29d?w=400&q=80", badge: "Local", descripcion: "Bombones de chocolate con leche en forma de piedras gallegas.", graduacion: null, volumen: "100 g", bodega: "Portomarín" },
  { id: 33, nombre: "Rocas de chocolate Costiña",          precio: 9.50,  categoria: "dulce", subcategoria: "chocolates", imagen: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&q=80", badge: null, descripcion: "Rocas de chocolate artesanal con frutos secos.", graduacion: null, volumen: "150 g", bodega: "Costiña" },
  { id: 34, nombre: "ALMENDRADOS DE ALLARIZ",              precio: 4.60,  categoria: "dulce", subcategoria: "otros",      imagen: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80", badge: "Local", descripcion: "Almendrados tradicionales de Allariz, Galicia.", graduacion: null, volumen: "200 g", bodega: "Allariz" },
  { id: 35, nombre: "Tarta de Almendras y Chocolate",      precio: 6.39,  categoria: "dulce", subcategoria: "otros",      imagen: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80", badge: null, descripcion: "Tarta artesanal de almendras y chocolate Ancano.", graduacion: null, volumen: "400 g", bodega: "Ancano" },
  { id: 36, nombre: "CASTAÑAS EN ALMÍBAR",                 precio: 6.40,  categoria: "dulce", subcategoria: "otros",      imagen: "https://images.unsplash.com/photo-1575377427642-087cf684f29d?w=400&q=80", badge: "Local", descripcion: "Castañas gallegas en almíbar, delicadeza tradicional.", graduacion: null, volumen: "300 g", bodega: "Galicia" },
  /* ── CERVEZA ── */
  { id: 37, nombre: "Cerveza Estrella Galicia 33 CL",      precio: 5.29,  categoria: "cerveza", subcategoria: "rubia",    imagen: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400&q=80", badge: "Más Vendido", descripcion: "La cerveza más famosa de Galicia, ligera y refrescante.", graduacion: "5,5%", volumen: "6x330 ml", bodega: "Estrella Galicia" },
  { id: 38, nombre: "Cerveza 1906 Reserva Especial",       precio: 5.27,  categoria: "cerveza", subcategoria: "especial", imagen: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400&q=80", badge: "Destacado", descripcion: "Cerveza de alta fermentación con más cuerpo y sabor intenso.", graduacion: "6,5%", volumen: "6x330 ml", bodega: "Estrella Galicia" },
  /* ── INFUSIONES ── */
  { id: 39, nombre: "Caja Selección Infusión",             precio: 8.55,  categoria: "infusiones", subcategoria: "te",    imagen: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80", badge: null, descripcion: "Caja selección con las mejores infusiones.", graduacion: null, volumen: "20 uds", bodega: "La Tetera Azul" },
  { id: 40, nombre: "Caja Premium Herbal Teas",            precio: 22.00, categoria: "infusiones", subcategoria: "te",    imagen: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&q=80", badge: "Premium", descripcion: "Selección premium de tés herbales de alta calidad.", graduacion: null, volumen: "30 uds", bodega: "La Tetera Azul" },
  { id: 41, nombre: "Roiboos Mediterráneo",                precio: 8.49,  categoria: "infusiones", subcategoria: "rooibos", imagen: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80", badge: null, descripcion: "Rooibos con notas mediterráneas, sin teína.", graduacion: null, volumen: "15 uds", bodega: "La Tetera Azul" },
  { id: 42, nombre: "Té Verde & Menta",                    precio: 7.36,  categoria: "infusiones", subcategoria: "te",    imagen: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&q=80", badge: null, descripcion: "Combinación refrescante de té verde y menta fresca.", graduacion: null, volumen: "15 uds", bodega: "La Tetera Azul" },
  { id: 43, nombre: "Ginger & Lemon",                      precio: 7.36,  categoria: "infusiones", subcategoria: "te",    imagen: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80", badge: "Novedad", descripcion: "Infusión de jengibre y limón, estimulante y digestiva.", graduacion: null, volumen: "15 uds", bodega: "La Tetera Azul" },
  { id: 44, nombre: "Manzanilla & Lavanda",                precio: 7.36,  categoria: "infusiones", subcategoria: "te",    imagen: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&q=80", badge: null, descripcion: "Infusión relajante de manzanilla y lavanda.", graduacion: null, volumen: "15 uds", bodega: "La Tetera Azul" },
];

const FEATURED_IDS = [1, 2, 3, 15, 17, 24, 26, 31, 37, 39, 20, 18];
const HIGHLIGHTED_IDS = [2, 1, 4, 9, 10, 7, 6, 8, 15, 18, 24, 25, 37, 38, 31, 39];

function getProductById(id) { return PRODUCTS.find(p => p.id === id); }
function getProductsByCategory(cat, sub) { return PRODUCTS.filter(p => sub ? p.subcategoria === sub : p.categoria === cat); }
function getFeaturedProducts() { return FEATURED_IDS.map(id => getProductById(id)).filter(Boolean); }
function getHighlightedProducts() { return HIGHLIGHTED_IDS.map(id => getProductById(id)).filter(Boolean); }
