const PRODUCTS = [
  { id: 1,  nombre: "Albariño Mar de Frades",         precio: 17.66, categoria: "vinos", subcategoria: "albarino",  imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80", badge: "Destacado",  descripcion: "Vino blanco gallego de la D.O. Rías Baixas con aromas a frutas tropicales y notas florales.", graduacion: "12,5%", volumen: "750 ml", bodega: "Mar de Frades" },
  { id: 2,  nombre: "Godello Valdeorras Avancia",     precio: 14.50, categoria: "vinos", subcategoria: "godello",   imagen: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&q=80", badge: null,        descripcion: "Vino blanco con carácter mineral y buena acidez, ideal con mariscos.", graduacion: "13%",   volumen: "750 ml", bodega: "Avancia" },
  { id: 3,  nombre: "Ribeiro Viña Meín",              precio: 12.90, categoria: "vinos", subcategoria: "ribeiro",   imagen: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80", badge: "Novedad",   descripcion: "Blanco fresco y aromático de la D.O. Ribeiro, elaborado con uvas Treixadura.", graduacion: "12%",   volumen: "750 ml", bodega: "Viña Meín" },
  { id: 4,  nombre: "Verdejo Naia",                   precio: 9.95,  categoria: "vinos", subcategoria: "verdejo",   imagen: "https://images.unsplash.com/photo-1546505575-5f0b8e6fa0c6?w=400&q=80", badge: null,        descripcion: "Verdejo 100% de Rueda con aromas herbáceos y final largo.", graduacion: "13%",   volumen: "750 ml", bodega: "Naia" },
  { id: 5,  nombre: "Ramón Bilbao Crianza",           precio: 10.50, categoria: "vinos", subcategoria: "rioja",     imagen: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80", badge: "Más Vendido", descripcion: "Tinto crianza de Rioja con 12 meses en barrica, notas de cereza y vainilla.", graduacion: "13,5%", volumen: "750 ml", bodega: "Ramón Bilbao" },
  { id: 6,  nombre: "Ribera Proventus Crianza",       precio: 20.09, categoria: "vinos", subcategoria: "ribera",    imagen: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&q=80", badge: null,        descripcion: "Tinto de Ribera del Duero con 18 meses en barrica francesa y americana.", graduacion: "14%",   volumen: "750 ml", bodega: "Proventus" },
  { id: 7,  nombre: "Mencía Joven Pago de Valpiedra", precio: 8.75,  categoria: "vinos", subcategoria: "mencia",    imagen: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&q=80", badge: null,        descripcion: "Joven frutal del Bierzo, ligero y con final agradable.", graduacion: "12,5%", volumen: "750 ml", bodega: "Valpiedra" },
  { id: 8,  nombre: "Rioja Centvm Vitis Gran Reserva",precio: 123.25,categoria: "vinos", subcategoria: "rioja",     imagen: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&q=80", badge: "Premium",   descripcion: "Gran Reserva excepcional con 36 meses en barrica. Vino de culto.", graduacion: "14,5%", volumen: "750 ml", bodega: "Centvm Vitis" },
  { id: 9,  nombre: "Peregrino Rosado",               precio: 4.99,  categoria: "vinos", subcategoria: "rosado",    imagen: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=400&q=80", badge: null,        descripcion: "Rosado fresco y frutal, perfecto para el verano.", graduacion: "12%",   volumen: "750 ml", bodega: "Peregrino" },
  { id: 10, nombre: "Ondipuerko Rosado Rioja",        precio: 15.16, categoria: "vinos", subcategoria: "rosado",    imagen: "https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=400&q=80", badge: "Destacado", descripcion: "Rosado moderno de Rioja con aromas a fresa fresca y pétalos de rosa.", graduacion: "12,5%", volumen: "750 ml", bodega: "Ondipuerko" },
  { id: 11, nombre: "Cava Brut Nature Reserva",       precio: 13.50, categoria: "vinos", subcategoria: "espumoso",  imagen: "https://images.unsplash.com/photo-1548198471-e5a4b27e7c72?w=400&q=80", badge: null,        descripcion: "Cava DO con 18 meses de crianza, burbujas finas y paladar seco.", graduacion: "11,5%", volumen: "750 ml", bodega: "Codorníu" },
  { id: 12, nombre: "Ginebra Cubical Premium",        precio: 22.51, categoria: "destilados", subcategoria: "ginebra", imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80", badge: "Destacado", descripcion: "Ginebra premium con aromas cítricos y botánicos seleccionados.", graduacion: "40%", volumen: "700 ml", bodega: "William & Humbert" },
  { id: 13, nombre: "Whisky Old Parr 1L",             precio: 42.93, categoria: "destilados", subcategoria: "whisky",  imagen: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&q=80", badge: null,        descripcion: "Blend escocés con 12 años de crianza, notas de miel y turba.", graduacion: "40%", volumen: "1000 ml", bodega: "Old Parr" },
  { id: 14, nombre: "Orujo Fillaboa Reserva Especial",precio: 42.93, categoria: "destilados", subcategoria: "orujo",   imagen: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&q=80", badge: "Más Vendido", descripcion: "Orujo gallego de alta calidad, suave y aromático.", graduacion: "40%", volumen: "700 ml", bodega: "Fillaboa" },
  { id: 15, nombre: "Ron Zacapa 23",                  precio: 38.00, categoria: "destilados", subcategoria: "ron",     imagen: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&q=80", badge: "Premium",   descripcion: "Ron guatemalteco añejo con notas de caramelo, vainilla y especias.", graduacion: "40%", volumen: "700 ml", bodega: "Zacapa" },
  { id: 16, nombre: "Brandy Lepanto Solera Gran Reserva", precio: 29.50, categoria: "destilados", subcategoria: "brandy", imagen: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80", badge: null, descripcion: "Brandy de Jerez con crianza en botas de Pedro Ximénez.", graduacion: "36%", volumen: "700 ml", bodega: "González Byass" },
  { id: 17, nombre: "Jamón Ibérico Bellota 50% 7Kg",  precio: 349.00,categoria: "gourmet", subcategoria: "jamon",  imagen: "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?w=400&q=80", badge: "Exclusivo", descripcion: "Jamón 50% ibérico de bellota, curación mínima 36 meses.", graduacion: null, volumen: "±7 Kg", bodega: "Covap" },
  { id: 18, nombre: "Queso Curado de Oveja 3 KG",     precio: 70.46, categoria: "gourmet", subcategoria: "quesos", imagen: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80", badge: null,        descripcion: "Queso curado de oveja de Zamora, sabor intenso y textura firme.", graduacion: null, volumen: "±3 Kg", bodega: "Sansueña" },
  { id: 19, nombre: "Chocolate Negro 95% Cacao",      precio: 3.39,  categoria: "gourmet", subcategoria: "chocolates", imagen: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&q=80", badge: null, descripcion: "Chocolate negro intenso, amargo y rico en polifenoles.", graduacion: null, volumen: "100 g", bodega: "Lindt" },
  { id: 20, nombre: "Bonito del Norte Ortiz 260g",    precio: 7.07,  categoria: "gourmet", subcategoria: "conservas", imagen: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80", badge: "Más Vendido", descripcion: "Bonito del norte en aceite de oliva virgen extra.", graduacion: null, volumen: "260 g", bodega: "Ortiz" },
];

const FEATURED_IDS = [1, 5, 12, 14, 8, 13, 18, 19];
const HIGHLIGHTED_IDS = [10, 1, 18, 7, 6, 8, 13, 20, 9, 5, 15, 3];

function getProductById(id) { return PRODUCTS.find(p => p.id === id); }
function getProductsByCategory(cat, sub = null) { return PRODUCTS.filter(p => sub ? p.subcategoria === sub : p.categoria === cat); }
function getFeaturedProducts() { return FEATURED_IDS.map(id => getProductById(id)).filter(Boolean); }
function getHighlightedProducts() { return HIGHLIGHTED_IDS.map(id => getProductById(id)).filter(Boolean); }