const PRODUCTS = [
  /* ── VINOS BLANCOS ── */
  { id: 1,  nombre: "Albariño Mar de Frades",          precio: 17.66, categoria: "vinos", subcategoria: "albarino",  imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80", badge: "Destacado",   descripcion: "Vino blanco gallego de la D.O. Rías Baixas con aromas a frutas tropicales y notas florales.", graduacion: "12,5%", volumen: "750 ml", bodega: "Mar de Frades" },
  { id: 2,  nombre: "Godello Valdeorras Avancia",      precio: 14.50, categoria: "vinos", subcategoria: "godello",   imagen: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&q=80", badge: null,          descripcion: "Vino blanco con carácter mineral y buena acidez, ideal con mariscos.", graduacion: "13%",   volumen: "750 ml", bodega: "Avancia" },
  { id: 3,  nombre: "Ribeiro Viña Meín",               precio: 12.90, categoria: "vinos", subcategoria: "ribeiro",   imagen: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80", badge: "Novedad",     descripcion: "Blanco fresco y aromático de la D.O. Ribeiro, elaborado con uvas Treixadura.", graduacion: "12%",   volumen: "750 ml", bodega: "Viña Meín" },
  { id: 4,  nombre: "Verdejo Naia",                    precio: 9.95,  categoria: "vinos", subcategoria: "verdejo",   imagen: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&q=80", badge: null,          descripcion: "Verdejo 100% de Rueda con aromas herbáceos y final largo.", graduacion: "13%",   volumen: "750 ml", bodega: "Naia" },
  { id: 21, nombre: "Albariño Pazo de Señorans",       precio: 19.90, categoria: "vinos", subcategoria: "albarino",  imagen: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&q=80", badge: "Premium",     descripcion: "Uno de los mejores Albariños de Rías Baixas, fresco y mineral.", graduacion: "13%",   volumen: "750 ml", bodega: "Pazo de Señorans" },
  { id: 22, nombre: "Godello Guitián Fermentado",      precio: 22.50, categoria: "vinos", subcategoria: "godello",   imagen: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=400&q=80", badge: "Destacado",   descripcion: "Godello fermentado en barrica con notas de mantequilla y fruta madura.", graduacion: "13,5%", volumen: "750 ml", bodega: "Guitián" },
  { id: 23, nombre: "Monterrei Pazos del Rey",         precio: 8.90,  categoria: "vinos", subcategoria: "monterrei", imagen: "https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=400&q=80", badge: null,          descripcion: "Blanco de la D.O. Monterrei, fresco y de fácil bebida.", graduacion: "12%",   volumen: "750 ml", bodega: "Pazos del Rey" },
  /* ── VINOS TINTOS ── */
  { id: 5,  nombre: "Ramón Bilbao Crianza",            precio: 10.50, categoria: "vinos", subcategoria: "rioja",     imagen: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80", badge: "Más Vendido", descripcion: "Tinto crianza de Rioja con 12 meses en barrica, notas de cereza y vainilla.", graduacion: "13,5%", volumen: "750 ml", bodega: "Ramón Bilbao" },
  { id: 6,  nombre: "Ribera Proventus Crianza",        precio: 20.09, categoria: "vinos", subcategoria: "ribera",    imagen: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&q=80", badge: null,          descripcion: "Tinto de Ribera del Duero con 18 meses en barrica francesa y americana.", graduacion: "14%",   volumen: "750 ml", bodega: "Proventus" },
  { id: 7,  nombre: "Mencía Joven Pago de Valpiedra", precio: 8.75,  categoria: "vinos", subcategoria: "mencia",    imagen: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80", badge: null,          descripcion: "Joven frutal del Bierzo, ligero y con final agradable.", graduacion: "12,5%", volumen: "750 ml", bodega: "Valpiedra" },
  { id: 8,  nombre: "Rioja Centvm Vitis Gran Reserva", precio: 123.25,categoria: "vinos", subcategoria: "rioja",     imagen: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&q=80", badge: "Premium",     descripcion: "Gran Reserva excepcional con 36 meses en barrica. Vino de culto.", graduacion: "14,5%", volumen: "750 ml", bodega: "Centvm Vitis" },
  { id: 24, nombre: "Ribeira Sacra Guímaro Tinto",     precio: 16.50, categoria: "vinos", subcategoria: "mencia",    imagen: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&q=80", badge: "Novedad",     descripcion: "Mencía de Ribeira Sacra con notas de frutas rojas y balsámicas.", graduacion: "13%",   volumen: "750 ml", bodega: "Guímaro" },
  { id: 25, nombre: "Valdeorras Rafael Palacios",      precio: 28.00, categoria: "vinos", subcategoria: "godello",   imagen: "https://images.unsplash.com/photo-1548198471-e5a4b27e7c72?w=400&q=80", badge: "Destacado",   descripcion: "Godello de alta expresión con crianza sobre lías finas.", graduacion: "13,5%", volumen: "750 ml", bodega: "Rafael Palacios" },
  /* ── ROSADOS Y ESPUMOSOS ── */
  { id: 9,  nombre: "Peregrino Rosado",                precio: 4.99,  categoria: "vinos", subcategoria: "rosado",    imagen: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=400&q=80", badge: null,          descripcion: "Rosado fresco y frutal, perfecto para el verano.", graduacion: "12%",   volumen: "750 ml", bodega: "Peregrino" },
  { id: 10, nombre: "Ondipuerko Rosado Rioja",         precio: 15.16, categoria: "vinos", subcategoria: "rosado",    imagen: "https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=400&q=80", badge: "Destacado",   descripcion: "Rosado moderno de Rioja con aromas a fresa fresca y pétalos de rosa.", graduacion: "12,5%", volumen: "750 ml", bodega: "Ondipuerko" },
  { id: 11, nombre: "Cava Brut Nature Reserva",        precio: 13.50, categoria: "vinos", subcategoria: "espumoso",  imagen: "https://images.unsplash.com/photo-1548198471-e5a4b27e7c72?w=400&q=80", badge: null,          descripcion: "Cava DO con 18 meses de crianza, burbujas finas y paladar seco.", graduacion: "11,5%", volumen: "750 ml", bodega: "Codorníu" },
  { id: 26, nombre: "Albariño Espumoso Fillaboa",      precio: 18.90, categoria: "vinos", subcategoria: "espumoso",  imagen: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80", badge: "Novedad",     descripcion: "Espumoso gallego elaborado con Albariño, burbujas finas y frescor atlántico.", graduacion: "11,5%", volumen: "750 ml", bodega: "Fillaboa" },
  /* ── DESTILADOS ── */
  { id: 12, nombre: "Ginebra Cubical Premium",         precio: 22.51, categoria: "destilados", subcategoria: "ginebra", imagen: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&q=80", badge: "Destacado",  descripcion: "Ginebra premium con aromas cítricos y botánicos seleccionados.", graduacion: "40%", volumen: "700 ml", bodega: "William & Humbert" },
  { id: 13, nombre: "Whisky Old Parr 1L",              precio: 42.93, categoria: "destilados", subcategoria: "whisky",  imagen: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&q=80", badge: null,         descripcion: "Blend escocés con 12 años de crianza, notas de miel y turba.", graduacion: "40%", volumen: "1000 ml", bodega: "Old Parr" },
  { id: 14, nombre: "Orujo Fillaboa Reserva Especial", precio: 42.93, categoria: "destilados", subcategoria: "orujo",   imagen: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&q=80", badge: "Más Vendido", descripcion: "Orujo gallego de alta calidad, suave y aromático.", graduacion: "40%", volumen: "700 ml", bodega: "Fillaboa" },
  { id: 15, nombre: "Ron Zacapa 23",                   precio: 38.00, categoria: "destilados", subcategoria: "ron",     imagen: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80", badge: "Premium",    descripcion: "Ron guatemalteco añejo con notas de caramelo, vainilla y especias.", graduacion: "40%", volumen: "700 ml", bodega: "Zacapa" },
  { id: 16, nombre: "Brandy Lepanto Solera Gran Reserva", precio: 29.50, categoria: "destilados", subcategoria: "brandy", imagen: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&q=80", badge: null, descripcion: "Brandy de Jerez con crianza en botas de Pedro Ximénez.", graduacion: "36%", volumen: "700 ml", bodega: "González Byass" },
  { id: 27, nombre: "Orujo de Hierbas Galicia",        precio: 14.50, categoria: "destilados", subcategoria: "orujo",   imagen: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&q=80", badge: null,         descripcion: "Licor de hierbas gallegas, suave y aromático. Ideal para digestivo.", graduacion: "30%", volumen: "700 ml", bodega: "Galicia" },
  { id: 28, nombre: "Ginebra Nordés Atlántica",        precio: 26.90, categoria: "destilados", subcategoria: "ginebra", imagen: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=400&q=80", badge: "Destacado",  descripcion: "Ginebra gallega con 11 botánicos autóctonos, sabor atlántico único.", graduacion: "40%", volumen: "700 ml", bodega: "Nordés" },
  /* ── GOURMET ── */
  { id: 17, nombre: "Jamón Ibérico Bellota 50% 7Kg",  precio: 349.00,categoria: "gourmet", subcategoria: "jamon",      imagen: "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?w=400&q=80", badge: "Exclusivo",  descripcion: "Jamón 50% ibérico de bellota, curación mínima 36 meses.", graduacion: null, volumen: "±7 Kg", bodega: "Covap" },
  { id: 18, nombre: "Queso Curado de Oveja 3 KG",     precio: 70.46, categoria: "gourmet", subcategoria: "quesos",     imagen: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80", badge: null,         descripcion: "Queso curado de oveja de Zamora, sabor intenso y textura firme.", graduacion: null, volumen: "±3 Kg", bodega: "Sansueña" },
  { id: 19, nombre: "Chocolate Negro 95% Cacao",      precio: 3.39,  categoria: "gourmet", subcategoria: "chocolates", imagen: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&q=80", badge: null,         descripcion: "Chocolate negro intenso, amargo y rico en polifenoles.", graduacion: null, volumen: "100 g", bodega: "Lindt" },
  { id: 20, nombre: "Bonito del Norte Ortiz 260g",    precio: 7.07,  categoria: "gourmet", subcategoria: "conservas",  imagen: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80", badge: "Más Vendido", descripcion: "Bonito del norte en aceite de oliva virgen extra.", graduacion: null, volumen: "260 g", bodega: "Ortiz" },
  { id: 29, nombre: "Tetilla D.O.P. Galicia 500g",    precio: 8.90,  categoria: "gourmet", subcategoria: "quesos",     imagen: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80", badge: "Local",       descripcion: "Queso gallego de forma cónica, suave y cremoso. Denominación de Origen.", graduacion: null, volumen: "500 g", bodega: "Galicia" },
  { id: 30, nombre: "Chorizo Galego Curado",          precio: 12.50, categoria: "gourmet", subcategoria: "embutidos",  imagen: "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?w=400&q=80", badge: null,         descripcion: "Chorizo gallego curado con pimentón de la Vera, sabor ahumado intenso.", graduacion: null, volumen: "400 g", bodega: "Lugo" },
  { id: 31, nombre: "Aceite de Oliva Virgen Extra",   precio: 9.95,  categoria: "gourmet", subcategoria: "conservas",  imagen: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&q=80", badge: null,         descripcion: "AOVE de primera extracción en frío, sabor afrutado y bajo acidez.", graduacion: null, volumen: "500 ml", bodega: "Andalucía" },
  { id: 32, nombre: "Percebes de Galicia 250g",       precio: 45.00, categoria: "gourmet", subcategoria: "conservas",  imagen: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80", badge: "Exclusivo",  descripcion: "Percebes frescos de la Costa da Morte, el marisco más exclusivo de Galicia.", graduacion: null, volumen: "250 g", bodega: "Costa da Morte" },
  /* ── CERVEZA ── */
  { id: 33, nombre: "Estrella Galicia Especial",      precio: 1.20,  categoria: "cerveza", subcategoria: "rubia",      imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80", badge: "Más Vendido", descripcion: "La cerveza más famosa de Galicia, ligera y refrescante.", graduacion: "5,5%", volumen: "330 ml", bodega: "Estrella Galicia" },
  { id: 34, nombre: "Estrella Galicia 1906 Reserva",  precio: 1.80,  categoria: "cerveza", subcategoria: "especial",   imagen: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&q=80", badge: "Destacado",   descripcion: "Cerveza de alta fermentación con más cuerpo y sabor intenso.", graduacion: "6,5%", volumen: "330 ml", bodega: "Estrella Galicia" },
  { id: 35, nombre: "Mahou Cinco Estrellas",          precio: 1.10,  categoria: "cerveza", subcategoria: "rubia",      imagen: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80", badge: null,          descripcion: "Cerveza rubia madrileña de sabor suave y equilibrado.", graduacion: "5,5%", volumen: "330 ml", bodega: "Mahou" },
  { id: 36, nombre: "Cerveza Artesana IPA Galicia",   precio: 3.50,  categoria: "cerveza", subcategoria: "artesana",   imagen: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&q=80", badge: "Novedad",     descripcion: "IPA gallega artesanal con lúpulos aromáticos y amargor equilibrado.", graduacion: "6%",   volumen: "330 ml", bodega: "Cervexería Galega" },
  { id: 37, nombre: "San Miguel Sin Alcohol",         precio: 0.99,  categoria: "cerveza", subcategoria: "sin alcohol", imagen: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=400&q=80", badge: null,         descripcion: "Cerveza sin alcohol refrescante y con todo el sabor.", graduacion: "0,0%", volumen: "330 ml", bodega: "San Miguel" },
  { id: 38, nombre: "Pack 6 Estrella Galicia",        precio: 6.50,  categoria: "cerveza", subcategoria: "rubia",      imagen: "https://images.unsplash.com/photo-1548198471-e5a4b27e7c72?w=400&q=80", badge: "Oferta",      descripcion: "Pack de 6 cervezas Estrella Galicia Especial.", graduacion: "5,5%", volumen: "6x330 ml", bodega: "Estrella Galicia" },
  /* ── CAFÉ ── */
  { id: 39, nombre: "Café Arábica Etiopía 250g",      precio: 8.90,  categoria: "cafe", subcategoria: "molido",        imagen: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&q=80", badge: "Destacado",   descripcion: "Café de especialidad de origen único, notas de frutas rojas y chocolate.", graduacion: null, volumen: "250 g", bodega: "Etiopía" },
  { id: 40, nombre: "Café Espresso Intenso",          precio: 6.50,  categoria: "cafe", subcategoria: "molido",        imagen: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80", badge: null,          descripcion: "Blend de café molido para espresso, sabor intenso y cremoso.", graduacion: null, volumen: "250 g", bodega: "Colombia" },
  { id: 41, nombre: "Cápsulas Nespresso Galicia",     precio: 5.90,  categoria: "cafe", subcategoria: "capsulas",      imagen: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&q=80", badge: "Novedad",     descripcion: "Cápsulas compatibles Nespresso con café gallego de tueste artesanal.", graduacion: null, volumen: "10 uds", bodega: "Galicia Café" },
  { id: 42, nombre: "Café Verde Adelgazante",         precio: 12.90, categoria: "cafe", subcategoria: "especial",      imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80", badge: null,          descripcion: "Café verde sin tostar con propiedades antioxidantes y estimulantes.", graduacion: null, volumen: "200 g", bodega: "Brasil" },
  { id: 43, nombre: "Té Verde Matcha Premium",        precio: 14.50, categoria: "cafe", subcategoria: "te",            imagen: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&q=80", badge: "Premium",     descripcion: "Matcha japonés de ceremonia, sabor suave y color vibrante.", graduacion: null, volumen: "100 g", bodega: "Japón" },
  { id: 44, nombre: "Café de Pota Galego",            precio: 7.20,  categoria: "cafe", subcategoria: "molido",        imagen: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=400&q=80", badge: "Local",       descripcion: "Blend tradicional gallego para preparar en cafetera de pota.", graduacion: null, volumen: "250 g", bodega: "Lugo" },
];

const FEATURED_IDS = [1, 5, 12, 14, 8, 13, 18, 19, 28, 33, 39, 21];
const HIGHLIGHTED_IDS = [10, 1, 18, 7, 6, 8, 13, 20, 9, 5, 15, 3, 33, 39, 29, 34];

function getProductById(id) { return PRODUCTS.find(p => p.id === id); }
function getProductsByCategory(cat, sub = null) { return PRODUCTS.filter(p => sub ? p.subcategoria === sub : p.categoria === cat); }
function getFeaturedProducts() { return FEATURED_IDS.map(id => getProductById(id)).filter(Boolean); }
function getHighlightedProducts() { return HIGHLIGHTED_IDS.map(id => getProductById(id)).filter(Boolean); }
